import type { Metadata } from "next";
import "../styles/globals.css";
import { LanguageGate } from "@/components/language-gate";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <LanguageGate />
        {children}
      </body>
    </html>
  );
}
